export { default as Login } from './login';
export { default as Varification } from './varification'
export { default as ForgotPassword } from './forgotPass'
export { default as F_Varification } from './F_Varification'
export { default as SetPassword } from './SetPassword'
export { default as register } from './register'
export { default as EditProfile } from './EditProfile'
export { default as DashBoard } from './Dashboard'
export { default as Action_Manager } from './Action_Manager'
export { default as AddContact } from './AddContact'
export { default as Edit_Contact } from './Edit_Contact'
export { default as Contacts } from './Contacts'
export { default as ReportFeedback } from './ReportFeedback'
export { default as Profile } from './Profile'
export { default as Report } from './Report';
export { default as Notification } from './Notification'
export { default as lead_manager } from './Lead_ Manager'
export { default as Task_Manager } from './Task_Manager'
export { default as AddTask } from './AddTask'
export { default as All_Lead } from './All_Lead'
export { default as addLead } from './addLead'
export { default as editLead } from './editLead'
export { default as Edit_Opportunity } from './Edit_Opportunity'
export { default as Report2 } from './Report2'
export { default as SideMenu } from './SideMenu'
export { default as History } from './History'
export { default as HistoryOne } from './HistoryOne'
export { default as History_Feedback } from './History_Feedback'
export { default as Splash } from './Splash'
export { default as Staff_Members } from './Staff_Members'
export { default as Organization } from './Organization'
export { default as Campaign } from './Campaign'
export { default as AddCampaign } from './AddCampaign'
export { default as EditCampaign } from './EditCampaign'
export { default as Meetings } from './Meetings'
export { default as AddMeetings } from './AddMeetings'
export { default as EditMeetings } from './EditMeetings'
export { default as MeetingsDetail } from './MeetingsDetail'
export { default as packegeTopups } from './packegeTopups'
export {default as orderHistory} from './orderHistory'
export {default as TransforLeads} from './TransforLeads'
export {default as LeadFilterScreen} from './LeadFilterScreen'
export {default as Lead_ManagerDetail} from './Lead_ManagerDetail'