export { default as Login } from '../screens/login/index';
export { default as Varification } from '../screens/varification/index'
export { default as ForgotPassword } from '../screens/forgotPass/index'
export { default as F_Varification } from '../screens/F_Varification/index'
export { default as SetPassword } from '../screens/SetPassword/index'
export { default as register } from '../screens/register/index'
export { default as EditProfile } from '../screens/EditProfile/index'
export { default as DashBoard } from '../screens/Dashboard/index'
export { default as Action_Manager } from './Action_Manager/index'
export { default as AddContactAsking } from "../screens/Add_contact_asking/index";
export { default as AddContactPopUp } from '../screens/Add_contact_popup/index'
export { default as AddContact } from '../screens/AddContact/index'
export { default as Edit_Contact } from '../screens/Edit_Contact/index'
export { default as Contacts } from '../screens/Contacts/index'
export { default as ContactsTwo } from '../screens/Contacts Two/index'
export { default as ReportFeedback } from '../screens/ReportFeedback/index'
export { default as AddContactUpload } from '../screens/AddContactUpload/index'
export { default as Profile } from '../screens/Profile/index'
export { default as Report } from '../screens/Report/index';
export { default as Notification } from '../screens/Notification/index'
export { default as lead_manager } from '../screens/Lead_ Manager/index'
export { default as Task_Manager } from '../screens/Task_Manager/index'
export {default as AddTask} from '../screens/AddTask'
export { default as All_Lead } from '../screens/All_Lead/index'
export { default as Edit_Lead } from '../screens/Edit_Lead/index'
export { default as Edit_Opportunity } from '../screens/Edit_Opportunity/index'
export { default as Report2 } from '../screens/Report2/index'
export { default as SideMenu } from '../screens/SideMenu'
export { default as History } from '../screens/History'
export { default as HistoryOne } from '../screens/HistoryOne'
export { default as History_Feedback } from '../screens/History_Feedback'
export { default as Splash } from '../screens/Splash'
export { default as Staff_Members } from '../screens/Staff_Members'
export { default as Organization } from '../screens/Organization'
export { default as Campaign } from '../screens/Campaign'
export { default as AddCampaign } from '../screens/AddCampaign'
export {default as EditCampaign } from '../screens/EditCampaign'

//stack screens

// export { default as HomeStack } from '../navigations/bottomStacksScreens/homeStack'
// export { default as ReportStack } from '../navigations/bottomStacksScreens/reportStack'
// export { default as IconStack } from '../navigations/bottomStacksScreens/iconStack'
// export { default as ContactStack } from '../navigations/bottomStacksScreens/contactStack'
// export { default as ProfileStack } from '../navigations/bottomStacksScreens/profileStack'